a = input('Digite algo...')
print('O que você digitou é do tipo', type(a))
print('Isso tem o valor de', len(a))
print('Tem espaço?', a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerica?', a.isalnum())
print('Esta em maiuscula?', a.isupper())
print('Esta em minuscula?', a.islower())
print('Esta capitalizada?', a.istitle())